"""Deterministic audit trail for every plan evaluation.

Explanations are built from recorded rule-evaluation data. Nothing here is
generated by a language model after the fact.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable

from ..messages import BLACKLIST_ACTION_REASON
from ..models import AuthorizationContext, FirewallAuditEvent, PlanEvaluation
from ..types import DecisionStatus, UserConfirmation

__all__ = [
    "AuditService",
    "PLAN_EVALUATION_EVENT",
    "ASK_RESOLUTION_EVENT",
    "BLACKLIST_ACTION_EVENT",
]

PLAN_EVALUATION_EVENT = "PLAN_EVALUATION"
ASK_RESOLUTION_EVENT = "ASK_RESOLUTION"
BLACKLIST_ACTION_EVENT = "BLACKLIST_ACTION"


class AuditService:
    """Collects audit events, optionally appending them to a JSONL file."""

    def __init__(
        self,
        path: str | Path | None = None,
        clock: Callable[[], datetime] | None = None,
    ) -> None:
        self._events: list[FirewallAuditEvent] = []
        self._sequence = 0
        self._path = Path(path) if path is not None else None
        self._clock: Callable[[], datetime] = clock or (
            lambda: datetime.now(timezone.utc)
        )

    # -- inspection ------------------------------------------------------
    @property
    def events(self) -> tuple[FirewallAuditEvent, ...]:
        return tuple(self._events)

    @property
    def path(self) -> Path | None:
        return self._path

    def __len__(self) -> int:
        return len(self._events)

    def to_jsonl(self) -> str:
        return "".join(
            json.dumps(event.to_dict(), sort_keys=True) + "\n" for event in self._events
        )

    # -- recording -------------------------------------------------------
    def record(
        self,
        evaluation: PlanEvaluation,
        context: AuthorizationContext,
        decision: DecisionStatus | None = None,
        reason: str | None = None,
        user_confirmation: UserConfirmation | None = None,
        merchant_blacklisted: bool | None = None,
        ask_id: str | None = None,
        event_type: str | None = None,
    ) -> FirewallAuditEvent:
        plan = evaluation.plan
        risk = evaluation.merchant_risk
        resolved_decision = decision if decision is not None else evaluation.status
        if event_type is None:
            event_type = (
                ASK_RESOLUTION_EVENT if ask_id is not None else PLAN_EVALUATION_EVENT
            )
        event = FirewallAuditEvent(
            id=self._next_id(),
            timestamp=self._clock().isoformat(),
            event_type=event_type,
            session_id=context.session_id,
            request_id=context.request_id,
            plan_rank=plan.rank,
            product_id=plan.product_id,
            merchant_id=plan.merchant_id,
            final_total=evaluation.final_total,
            daily_spent_before=context.daily_spent,
            projected_daily_spent=context.daily_spent + evaluation.final_total,
            evaluated_rules=evaluation.evaluated_rules,
            passed_rules=evaluation.passed_rules,
            failed_rules=evaluation.failed_rules,
            merchant_credit_score=None if risk is None else risk.merchant_credit_score,
            buyer_feedback_score=None if risk is None else risk.buyer_feedback_score,
            merchant_rating=None if risk is None else risk.merchant_rating,
            risk_level=None if risk is None else risk.risk_level,
            decision=resolved_decision,
            reason=reason if reason is not None else evaluation.reason,
            user_confirmation=user_confirmation,
            merchant_blacklisted=merchant_blacklisted,
            ask_id=ask_id,
        )
        self._append(event)
        return event

    def record_blacklist_action(
        self,
        evaluation: PlanEvaluation,
        context: AuthorizationContext,
        ask_id: str | None = None,
    ) -> FirewallAuditEvent:
        """Record that the user chose to blacklist the merchant during an ASK."""

        return self.record(
            evaluation,
            context,
            decision=DecisionStatus.APPROVE,
            reason=BLACKLIST_ACTION_REASON,
            user_confirmation=UserConfirmation.CONFIRMED,
            merchant_blacklisted=True,
            ask_id=ask_id,
            event_type=BLACKLIST_ACTION_EVENT,
        )

    # -- internals -------------------------------------------------------
    def _next_id(self) -> str:
        self._sequence += 1
        return f"audit-{self._sequence:06d}"

    def _append(self, event: FirewallAuditEvent) -> None:
        self._events.append(event)
        if self._path is None:
            return
        self._path.parent.mkdir(parents=True, exist_ok=True)
        with self._path.open("a", encoding="utf-8") as handle:
            handle.write(json.dumps(event.to_dict(), sort_keys=True) + "\n")
